// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package keybroker

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyBrokerResponse struct {
	_tab flatbuffers.Table
}

const KeyBrokerResponseIdentifier = "OBKS"

func GetRootAsKeyBrokerResponse(buf []byte, offset flatbuffers.UOffsetT) *KeyBrokerResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyBrokerResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyBrokerResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(KeyBrokerResponseIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func KeyBrokerResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, KeyBrokerResponseIdentifier)
}

func GetSizePrefixedRootAsKeyBrokerResponse(buf []byte, offset flatbuffers.UOffsetT) *KeyBrokerResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyBrokerResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyBrokerResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(KeyBrokerResponseIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedKeyBrokerResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, KeyBrokerResponseIdentifier)
}

func (rcv *KeyBrokerResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyBrokerResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyBrokerResponse) Status() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyBrokerResponse) MutateStatus(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *KeyBrokerResponse) Packet(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *KeyBrokerResponse) PacketLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *KeyBrokerResponse) PacketBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyBrokerResponse) MutatePacket(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func KeyBrokerResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KeyBrokerResponseAddStatus(builder *flatbuffers.Builder, status uint32) {
	builder.PrependUint32Slot(0, status, 0)
}
func KeyBrokerResponseAddPacket(builder *flatbuffers.Builder, packet flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(packet), 0)
}
func KeyBrokerResponseStartPacketVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func KeyBrokerResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
