// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package keybroker

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyBrokerRequest struct {
	_tab flatbuffers.Table
}

const KeyBrokerRequestIdentifier = "OBKQ"

func GetRootAsKeyBrokerRequest(buf []byte, offset flatbuffers.UOffsetT) *KeyBrokerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyBrokerRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyBrokerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(KeyBrokerRequestIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func KeyBrokerRequestBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, KeyBrokerRequestIdentifier)
}

func GetSizePrefixedRootAsKeyBrokerRequest(buf []byte, offset flatbuffers.UOffsetT) *KeyBrokerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyBrokerRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyBrokerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(KeyBrokerRequestIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedKeyBrokerRequestBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, KeyBrokerRequestIdentifier)
}

func (rcv *KeyBrokerRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyBrokerRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyBrokerRequest) Packet(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *KeyBrokerRequest) PacketLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *KeyBrokerRequest) PacketBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyBrokerRequest) MutatePacket(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func KeyBrokerRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KeyBrokerRequestAddPacket(builder *flatbuffers.Builder, packet flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(packet), 0)
}
func KeyBrokerRequestStartPacketVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func KeyBrokerRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
