// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package keybroker

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PublicKeyResponse struct {
	_tab flatbuffers.Table
}

const PublicKeyResponseIdentifier = "OBPK"

func GetRootAsPublicKeyResponse(buf []byte, offset flatbuffers.UOffsetT) *PublicKeyResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PublicKeyResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPublicKeyResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(PublicKeyResponseIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func PublicKeyResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, PublicKeyResponseIdentifier)
}

func GetSizePrefixedRootAsPublicKeyResponse(buf []byte, offset flatbuffers.UOffsetT) *PublicKeyResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PublicKeyResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPublicKeyResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(PublicKeyResponseIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedPublicKeyResponseBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, PublicKeyResponseIdentifier)
}

func (rcv *PublicKeyResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PublicKeyResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PublicKeyResponse) PublicKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PublicKeyResponse) PublicKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PublicKeyResponse) PublicKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PublicKeyResponse) MutatePublicKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func PublicKeyResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PublicKeyResponseAddPublicKey(builder *flatbuffers.Builder, publicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(publicKey), 0)
}
func PublicKeyResponseStartPublicKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PublicKeyResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
